### ISSUE TITLE
unify kbe and be pfrags.Frags class

### ISSUE THREAD

**Issue by mcocdawc** [troyvvgroup/quemb#38]
There seems to be a low-hanging fruit of shared functionality.

**Comment by lweisburn** [comment]
Even if there is shared functionality now, I think we should keep these separate. The periodic fragmentation can be far more complicated/bug-prone than the molecular version, and I would much rather develop in one or the other separately. I don't think this isn't really a place where efficiency/optimization is necessary, and readability will be far more important/useful

**Comment by mcocdawc** [comment]
aye, aye :-)
